export enum TipoCalificacion {

  TITULO = 'TITULO',
  DESCRIPCION = 'DESCRIPCION',
  POBLACION_OBJETIVO = 'POBLACION_OBJETIVO',
  JUSTIFICACION = 'JUSTIFICACION',
  PRESUPUESTO = 'PRESUPUESTO',
  RESULTADOS_ESPERADOS = 'RESULTADOS_ESPERADOS',
  ARBOL_PROBLEMAS = 'ARBOL_PROBLEMAS',
  CAUSA = 'CAUSA',
  EFECTO = 'EFECTO',
  ARBOL_OBJETIVOS = 'ARBOL_OBJETIVOS',
  MEDIO = 'MEDIO',
  FIN = 'FIN'

}



