spring.application.name=dafe

# Configuraci�n de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/dafe?useSSL=false&serverTimezone=UTC&useLegacyDateTimeCode=false
spring.datasource.username=root
spring.datasource.password=

# SQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto= update

# spring.jpa.properties.hibernate.format_sql=true
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Set Time Zone 
spring.jackson.time-zone=America/Bogota
spring.jpa.properties.hibernate.jdbc.time_zone=America/Bogota

# Security
jwt.secret=claveSecretaSuperLargaYSeguraParaGenerarTokensJWT123456789
jwt.expiration=172800000

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cteidafepopayan@gmail.com
#spring.mail.password=${MAIL_APP_PASSWORD}
spring.mail.password=koiefqooyckcucou
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.urlFront=http://localhost:4200/email/change-password/


##################################################
# DAFE
##################################################

dafe.export.secret=MiClaveSuperSecretaDAFE2026@

dafe.export.system=DAFE
dafe.export.version=2
dafe.export.module=PROYECTOS
dafe.export.type=PROYECTO
dafe.export.format=EXPORT_V2